package com.river.activiti.dao.mapper;

import com.river.activiti.model.pojo.BackendRole;

import java.util.List;

public interface BackendRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int insert(BackendRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int insertSelective(BackendRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    BackendRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int updateByPrimaryKeySelective(BackendRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int updateByPrimaryKey(BackendRole record);

    List<BackendRole> queryBackendRoleByUserId(Long id);
}