package com.river.activiti.dao.mapper;

import com.river.activiti.model.pojo.BackendUserRole;

public interface BackendUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int insert(BackendUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int insertSelective(BackendUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    BackendUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int updateByPrimaryKeySelective(BackendUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user_role
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    int updateByPrimaryKey(BackendUserRole record);
}