package com.river.activiti.dao.mapper;

import com.river.activiti.model.pojo.Leave;

public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbggenerated Wed Nov 08 10:56:41 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbggenerated Wed Nov 08 10:56:41 CST 2017
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbggenerated Wed Nov 08 10:56:41 CST 2017
     */
    int insertSelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbggenerated Wed Nov 08 10:56:41 CST 2017
     */
    Leave selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbggenerated Wed Nov 08 10:56:41 CST 2017
     */
    int updateByPrimaryKeySelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbggenerated Wed Nov 08 10:56:41 CST 2017
     */
    int updateByPrimaryKey(Leave record);
}