package com.river.activiti.dao.mapper;

import com.river.activiti.model.pojo.LeaveBill;

import java.util.List;

public interface LeaveBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_bill
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_bill
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    int insert(LeaveBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_bill
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    int insertSelective(LeaveBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_bill
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    LeaveBill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_bill
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    int updateByPrimaryKeySelective(LeaveBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_bill
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    int updateByPrimaryKey(LeaveBill record);


    List<LeaveBill> findLeaveBillByUserId(Long id);
}