package com.river.activiti.model.pojo;

import java.util.Date;

public class BackendRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.en_name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.cn_name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private String cnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.memo
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.create_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.update_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.gmt_create
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.gmt_modified
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.enable_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Boolean enableDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_role.is_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.id
     *
     * @return the value of backend_role.id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.id
     *
     * @param id the value for backend_role.id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.en_name
     *
     * @return the value of backend_role.en_name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.en_name
     *
     * @param enName the value for backend_role.en_name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.cn_name
     *
     * @return the value of backend_role.cn_name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.cn_name
     *
     * @param cnName the value for backend_role.cn_name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setCnName(String cnName) {
        this.cnName = cnName == null ? null : cnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.memo
     *
     * @return the value of backend_role.memo
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.memo
     *
     * @param memo the value for backend_role.memo
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.create_by
     *
     * @return the value of backend_role.create_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.create_by
     *
     * @param createBy the value for backend_role.create_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.update_by
     *
     * @return the value of backend_role.update_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.update_by
     *
     * @param updateBy the value for backend_role.update_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.gmt_create
     *
     * @return the value of backend_role.gmt_create
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.gmt_create
     *
     * @param gmtCreate the value for backend_role.gmt_create
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.gmt_modified
     *
     * @return the value of backend_role.gmt_modified
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.gmt_modified
     *
     * @param gmtModified the value for backend_role.gmt_modified
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.enable_delete
     *
     * @return the value of backend_role.enable_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Boolean getEnableDelete() {
        return enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.enable_delete
     *
     * @param enableDelete the value for backend_role.enable_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setEnableDelete(Boolean enableDelete) {
        this.enableDelete = enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_role.is_delete
     *
     * @return the value of backend_role.is_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_role.is_delete
     *
     * @param isDelete the value for backend_role.is_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}