package com.river.activiti.model.pojo;

import java.util.Date;

public class BackendUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user_role.id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user_role.backend_user_id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long backendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user_role.backend_role_id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long backendRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user_role.create_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user_role.update_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user_role.gmt_create
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user_role.gmt_modified
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user_role.is_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user_role.id
     *
     * @return the value of backend_user_role.id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user_role.id
     *
     * @param id the value for backend_user_role.id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user_role.backend_user_id
     *
     * @return the value of backend_user_role.backend_user_id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getBackendUserId() {
        return backendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user_role.backend_user_id
     *
     * @param backendUserId the value for backend_user_role.backend_user_id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setBackendUserId(Long backendUserId) {
        this.backendUserId = backendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user_role.backend_role_id
     *
     * @return the value of backend_user_role.backend_role_id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getBackendRoleId() {
        return backendRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user_role.backend_role_id
     *
     * @param backendRoleId the value for backend_user_role.backend_role_id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setBackendRoleId(Long backendRoleId) {
        this.backendRoleId = backendRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user_role.create_by
     *
     * @return the value of backend_user_role.create_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user_role.create_by
     *
     * @param createBy the value for backend_user_role.create_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user_role.update_by
     *
     * @return the value of backend_user_role.update_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user_role.update_by
     *
     * @param updateBy the value for backend_user_role.update_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user_role.gmt_create
     *
     * @return the value of backend_user_role.gmt_create
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user_role.gmt_create
     *
     * @param gmtCreate the value for backend_user_role.gmt_create
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user_role.gmt_modified
     *
     * @return the value of backend_user_role.gmt_modified
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user_role.gmt_modified
     *
     * @param gmtModified the value for backend_user_role.gmt_modified
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user_role.is_delete
     *
     * @return the value of backend_user_role.is_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user_role.is_delete
     *
     * @param isDelete the value for backend_user_role.is_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}