package com.river.activiti.model.pojo;

import java.util.Date;

public class BackendUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.reality_name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private String realityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.mobile
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.password
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.status
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.is_frozen
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Boolean isFrozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.private_salt
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private String privateSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.last_login_time
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.create_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.update_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.gmt_create
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.gmt_modified
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.is_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backend_user.id_card_no
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    private String idCardNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.id
     *
     * @return the value of backend_user.id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.id
     *
     * @param id the value for backend_user.id
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.name
     *
     * @return the value of backend_user.name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.name
     *
     * @param name the value for backend_user.name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.reality_name
     *
     * @return the value of backend_user.reality_name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public String getRealityName() {
        return realityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.reality_name
     *
     * @param realityName the value for backend_user.reality_name
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setRealityName(String realityName) {
        this.realityName = realityName == null ? null : realityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.mobile
     *
     * @return the value of backend_user.mobile
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.mobile
     *
     * @param mobile the value for backend_user.mobile
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.password
     *
     * @return the value of backend_user.password
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.password
     *
     * @param password the value for backend_user.password
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.status
     *
     * @return the value of backend_user.status
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.status
     *
     * @param status the value for backend_user.status
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.is_frozen
     *
     * @return the value of backend_user.is_frozen
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Boolean getIsFrozen() {
        return isFrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.is_frozen
     *
     * @param isFrozen the value for backend_user.is_frozen
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setIsFrozen(Boolean isFrozen) {
        this.isFrozen = isFrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.private_salt
     *
     * @return the value of backend_user.private_salt
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public String getPrivateSalt() {
        return privateSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.private_salt
     *
     * @param privateSalt the value for backend_user.private_salt
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setPrivateSalt(String privateSalt) {
        this.privateSalt = privateSalt == null ? null : privateSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.last_login_time
     *
     * @return the value of backend_user.last_login_time
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.last_login_time
     *
     * @param lastLoginTime the value for backend_user.last_login_time
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.create_by
     *
     * @return the value of backend_user.create_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.create_by
     *
     * @param createBy the value for backend_user.create_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.update_by
     *
     * @return the value of backend_user.update_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.update_by
     *
     * @param updateBy the value for backend_user.update_by
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.gmt_create
     *
     * @return the value of backend_user.gmt_create
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.gmt_create
     *
     * @param gmtCreate the value for backend_user.gmt_create
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.gmt_modified
     *
     * @return the value of backend_user.gmt_modified
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.gmt_modified
     *
     * @param gmtModified the value for backend_user.gmt_modified
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.is_delete
     *
     * @return the value of backend_user.is_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.is_delete
     *
     * @param isDelete the value for backend_user.is_delete
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backend_user.id_card_no
     *
     * @return the value of backend_user.id_card_no
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backend_user.id_card_no
     *
     * @param idCardNo the value for backend_user.id_card_no
     *
     * @mbggenerated Tue Dec 05 14:14:24 CST 2017
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }
}