package com.river.activiti.model.pojo;

import java.util.Date;

public class Leave {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.id
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.user_id
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.leave_reason
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private String leaveReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.leave_days
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Integer leaveDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.status
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.start_time
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.end_time
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.create_by
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.update_by
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.gmt_create
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.gmt_modified
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.is_delete
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.id
     *
     * @return the value of leave.id
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.id
     *
     * @param id the value for leave.id
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.user_id
     *
     * @return the value of leave.user_id
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.user_id
     *
     * @param userId the value for leave.user_id
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.leave_reason
     *
     * @return the value of leave.leave_reason
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public String getLeaveReason() {
        return leaveReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.leave_reason
     *
     * @param leaveReason the value for leave.leave_reason
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setLeaveReason(String leaveReason) {
        this.leaveReason = leaveReason == null ? null : leaveReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.leave_days
     *
     * @return the value of leave.leave_days
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Integer getLeaveDays() {
        return leaveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.leave_days
     *
     * @param leaveDays the value for leave.leave_days
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setLeaveDays(Integer leaveDays) {
        this.leaveDays = leaveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.status
     *
     * @return the value of leave.status
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.status
     *
     * @param status the value for leave.status
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.start_time
     *
     * @return the value of leave.start_time
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.start_time
     *
     * @param startTime the value for leave.start_time
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.end_time
     *
     * @return the value of leave.end_time
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.end_time
     *
     * @param endTime the value for leave.end_time
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.create_by
     *
     * @return the value of leave.create_by
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.create_by
     *
     * @param createBy the value for leave.create_by
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.update_by
     *
     * @return the value of leave.update_by
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.update_by
     *
     * @param updateBy the value for leave.update_by
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.gmt_create
     *
     * @return the value of leave.gmt_create
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.gmt_create
     *
     * @param gmtCreate the value for leave.gmt_create
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.gmt_modified
     *
     * @return the value of leave.gmt_modified
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.gmt_modified
     *
     * @param gmtModified the value for leave.gmt_modified
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.is_delete
     *
     * @return the value of leave.is_delete
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.is_delete
     *
     * @param isDelete the value for leave.is_delete
     *
     * @mbggenerated Thu Nov 09 10:42:21 CST 2017
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}