package com.river.activiti.model.pojo;

import java.util.Date;

public class LeaveBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_bill.id
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_bill.days
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_bill.content
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_bill.leave_date
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    private Date leaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_bill.remark
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_bill.user_id
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_bill.state
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_bill.id
     *
     * @return the value of leave_bill.id
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_bill.id
     *
     * @param id the value for leave_bill.id
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_bill.days
     *
     * @return the value of leave_bill.days
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_bill.days
     *
     * @param days the value for leave_bill.days
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_bill.content
     *
     * @return the value of leave_bill.content
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_bill.content
     *
     * @param content the value for leave_bill.content
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_bill.leave_date
     *
     * @return the value of leave_bill.leave_date
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_bill.leave_date
     *
     * @param leaveDate the value for leave_bill.leave_date
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_bill.remark
     *
     * @return the value of leave_bill.remark
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_bill.remark
     *
     * @param remark the value for leave_bill.remark
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_bill.user_id
     *
     * @return the value of leave_bill.user_id
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_bill.user_id
     *
     * @param userId the value for leave_bill.user_id
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_bill.state
     *
     * @return the value of leave_bill.state
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_bill.state
     *
     * @param state the value for leave_bill.state
     *
     * @mbggenerated Sun Nov 12 20:11:02 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }
}